---
name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      #- uses: lowlighter/metrics@latest
      - uses: stalomeow/metrics@edcae0f874d69e509d25ddd5e750a2f41cd54e10
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_achievements: yes
